# Generated by Django 3.1.8 on 2021-04-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='company_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='John', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
