# Generated by Django 3.1.8 on 2021-04-26 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.sponsor'),
        ),
    ]
