# Generated by Django 3.1.8 on 2021-04-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='sponsor',
            new_name='sponsor1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.sponsor'),
        ),
    ]
