# Generated by Django 3.1.8 on 2021-04-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sportnewspost_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_post_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.sportnewspost'),
        ),
    ]
