# Generated by Django 3.1.8 on 2021-04-30 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0015_homepage_news_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='adv_sport_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_post_left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.sportnewspost'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_post_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.sportnewspost'),
        ),
    ]
