# Generated by Django 3.1.8 on 2021-05-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210501_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportnewspost',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
