# Generated by Django 3.1.8 on 2021-05-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_sportnewspost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=100)),
                ('match_location', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('club_name', models.CharField(max_length=100)),
                ('against_name', models.CharField(default='Other team', max_length=100)),
                ('score_home', models.IntegerField(default='0')),
                ('score_other_team', models.IntegerField(default='0')),
                ('club_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('other_club_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='last_game_home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.matchinfo'),
        ),
    ]
