# Generated by Django 3.1.8 on 2021-05-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210503_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='next_game_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.matchinfo'),
        ),
    ]
