# Generated by Django 3.1.8 on 2021-05-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homepage_next_game_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeagueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_position', models.IntegerField(max_length=2)),
                ('team_name', models.CharField(max_length=100)),
                ('games_played', models.IntegerField(max_length=2)),
                ('goals_diff', models.IntegerField(max_length=3)),
                ('points', models.IntegerField(max_length=3)),
                ('team_logo', models.CharField(default='Other team', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='league_table_team_info_pos1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teamleaguedetail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='league_table_team_info_pos2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teamleaguedetail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='league_table_team_info_pos3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teamleaguedetail'),
        ),
    ]
