# Generated by Django 3.1.8 on 2021-05-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0021_auto_20210503_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleaguedetail',
            name='team_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
