# Generated by Django 3.1.8 on 2021-05-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210503_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.sportnewspost'),
        ),
    ]
